# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 02:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20170710_1844'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pets',
            managers=[
                ('petManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='pets',
            name='contact',
        ),
    ]
