# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20170710_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptions',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='adoptions',
            name='user',
        ),
        migrations.AddField(
            model_name='pets',
            name='adopted',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='pets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pets', to='shelter.Users'),
        ),
        migrations.DeleteModel(
            name='Adoptions',
        ),
    ]
