# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_auto_20170719_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='pic_url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
