# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_pets_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='approved',
            field=models.BooleanField(default=None),
        ),
    ]
