# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-31 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_pets_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Pets', to='shelter.Users'),
        ),
    ]
